export enum Gender {
  Male = 0,
  Female = 1,
}
export enum BusinessUnit {
  AKC = 0,
  AMCL = 1,
  APCL = 2,
  Africa = 3,
  BBL = 4,
  BBML = 5,
  BBMT = 6,
  BML = 7,
  Best_Buy = 8,
  DPL = 9,
  Dairy = 10,
  Export_Common = 11,
  Getwell = 12,
  Gulf = 13,
  India = 14,
  KSA = 15,
  Kuwait = 16,
  MLIL = 17,
  Malaysia = 18,
  NAL = 19,
  PAL = 20,
  PBL = 21,
  PCL = 22,
  PDL = 23,
  PFF = 24,
  PFL = 25,
  PSC = 26,
  Philippines = 27,
  REL = 28,
  RFL_Bike = 29,
  RFL_Stationery = 30,
  RMIL = 31,
  RMIL_3 = 32,
  RPL = 33,
  RPLE = 34,
  Retail = 35,
  SAARC = 36,
  Tasty_Treat = 37,
  UAE = 38,
  UK = 39,
  USA_Europe = 40,
  RMIL_1 = 41,
  RFL_TVS = 42,
  RFL_RYDO = 43,
  RPLM = 44,
  RFL_Vision = 45
}
export enum WorkType {
  ATC_Box = 0,
  ATC_Box_Output = 1,
  Background_Remove = 2,
  Image_Resize = 3,
  Black_Cylinder_Output = 4,
  Branding = 5,
  Carton_Design = 6,
  Clipping_Path = 7,
  Digital_Static_For_Social_Media = 8,
  Document_Text_Correction = 9,
  FOP_Sticker_Making = 10,
  Flyer_Brochure_Banner_Output = 11,
  Full_Cylinder_Output = 12,
  Gravure_Output_1 = 13,
  Gravure_Output_2 = 14,
  JAR_Label_Sticker_Output = 15,
  Layout_Dieline_Making = 16,
  Leaflet_Poster_Output = 17,
  Logo_Design = 18,
  Outdoor_Event_Showroom_Branding = 19,
  Output_Setup_Gravure_Offset = 20,
  Packaging = 21,
  Packaging_Text_Design_1 = 22,
  Packaging_Text_Design_2 = 23,
  Text_Sticker_Design_1 = 24,
  Text_Sticker_Design_2 = 25,
  Visiting_ID_Card_Design = 26,
  Voice_Over = 27,
  Packing_Label = 28
}
export enum SubType {
  New = 0,
  Revision = 1,
}
export enum ProjectStatus {
  BM_Approved = 0,
  Brief_Submitted = 1,
  HoM_Approved = 2,
  In_Review = 3,
  Running = 4,
  Canceled = 5,
  Revision = 6
}